version: 0.2

phases:
  install:
    commands:
      - echo "Install phase started"

  pre_build:
    commands:
      - echo "Starting Docker build process"
      - docker --version

  build:
    commands:
      - echo "Building Docker image"
      - docker build -t myapp .

      - echo "Running container"
      - docker run myapp

  post_build:
    commands:
      - echo "Build completed successfully"
